# Generated by Django 4.2.6 on 2025-07-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='mehdi', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
