# Generated by Django 4.2.6 on 2025-07-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Optional username for the user.', max_length=50, null=True, unique=True),
        ),
    ]
