# Generated by Django 4.2.6 on 2025-07-30 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text="User's email address, used for account recovery or additional identification.", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text="User's phone number, used as the primary login identifier (e.g., +1234567890).", max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be 9-15 digits, optionally starting with '+'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
