# Generated by Django 4.2.6 on 2025-08-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text="User's email address, used for account recovery or additional identification.", max_length=254, null=True, unique=True),
        ),
    ]
