# Generated by Django 4.2.6 on 2025-08-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='custom_user_email_55dec9_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
