# Generated by Django 4.2.6 on 2025-08-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_customuser_custom_user_email_55dec9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='national_code',
            field=models.PositiveIntegerField(default=2051229732, help_text="User's national code.", max_length=10),
            preserve_default=False,
        ),
    ]
