# Generated by Django 4.2.6 on 2025-08-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_customuser_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_code',
            field=models.IntegerField(blank=True, help_text="User's national code.", max_length=10, null=True),
        ),
    ]
