# Generated by Django 4.2.6 on 2025-05-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('telegram_link', models.URLField(max_length=250)),
                ('eitaa_link', models.URLField(max_length=250)),
            ],
        ),
    ]
