# Generated by Django 4.2.6 on 2025-05-25 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='register_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=38)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('statement', models.CharField(choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('البرز', 'البرز'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('خراسان جنوبی', 'خراسان جنوبی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان شمالی', 'خراسان شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('فارس', 'فارس'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کردستان', 'کردستان'), ('کرمانشاه', 'کرمانشاه'), ('کرمان', 'کرمان'), ('کهکیلویه و بویراحمد', 'کهکیلویه و بویراحمد'), ('گلستان', 'گلستان'), ('گیلان', 'گیلان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('هرمزگان', 'هرمزگان'), ('مرکزی', 'مرکزی'), ('همدان', 'همدان'), ('یزد', 'یزد')], max_length=45)),
                ('cooperation_kind', models.CharField(choices=[('individual', 'فرد'), ('company', 'شرکت')], max_length=25)),
                ('skill', models.CharField(blank=True, choices=[('civil engineering', 'مهندسی عمران'), ('architectural engineering', 'مهندسی معمار'), ('electricity engineering', 'مهندسی برق'), ('facilities engineering', 'مهندسی تاسیسات'), ('surveyor', 'نقشه بردار'), ('mechanical machinery operator', 'اپراتور ماشین الات مکانیکی'), ('electerical technician', 'تکنسین برق'), ('plasterer', 'گچکار'), ('plumber', 'لوله کش'), ('painter', 'نقاش'), ('insulation specialist', 'متخصص عایقکاری'), ('brick layer', 'بنا'), ('mechanical installation technician', 'تکنسین تاسیسات مکانیکی'), ('carpenter', 'نجار'), ('tile work', 'کاشی کار'), ('stone work', 'سنگ کار'), ('simple worker', 'کارگر ساده'), ('interior designer', 'طراح داخلی'), ('building supervisor', 'ناظر ساختمان'), ('armatorband', 'آرماتور بند'), ('welder', 'جوشکار'), ('metal skeleton specialist', 'متخصص اسکلت فلزی'), ('elevator installer', 'نصاب آسانسور'), ('security systems installer', 'نصاب سیستم های امنیتی'), ('renewable energy specialist', 'متخصص انرژی های تجدید پذیر'), ('waste expert', 'کارشناس پسماند'), ('building materials seller', 'فروشنده مصالح ساختمانی'), ('purchasing manager', 'مدیر خرید'), ('building cleaner', 'نظافتچی ساختمان'), ('heavy machinery operator', 'اپراتور ماشین آلات سنگین'), ('smart systems installer', 'نصاب سیستم های هوشمند')], max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], default='active', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/register-ad/')),
                ('register_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='register_ad.register_ad')),
            ],
        ),
    ]
