# Generated by Django 4.2.6 on 2025-07-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_for_confirmation', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='register_ad',
            name='register_request',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='register_ad.register_request'),
            preserve_default=False,
        ),
    ]
