# Generated by Django 4.2.6 on 2025-07-04 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0002_register_request_register_ad_register_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_ad',
            name='register_request',
        ),
        migrations.AddField(
            model_name='register_request',
            name='ad',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='register_request_set', to='register_ad.register_ad'),
            preserve_default=False,
        ),
    ]
