# Generated by Django 4.2.6 on 2025-07-04 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register_ad', '0003_remove_register_ad_register_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_request',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='register_request',
            unique_together={('ad', 'user')},
        ),
        migrations.AlterModelTable(
            name='register_ad',
            table='ad',
        ),
        migrations.AlterModelTable(
            name='register_request',
            table='register_request',
        ),
    ]
