# Generated by Django 4.2.6 on 2025-07-05 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register_ad', '0004_register_request_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='register_request',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='register_request',
            name='message',
            field=models.CharField(default='hello', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_request',
            name='recipient_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='recipient_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_request',
            name='sender_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='register_request',
            unique_together={('ad', 'sender_user')},
        ),
        migrations.RemoveField(
            model_name='register_request',
            name='user',
        ),
    ]
