# Generated by Django 4.2.6 on 2025-07-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0005_alter_register_request_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_request',
            name='description',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_request',
            name='first_name',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_request',
            name='gender',
            field=models.CharField(choices=[('MALE', 'مرد'), ('FEMALE', 'زن')], default='1', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_request',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='register_request',
            name='last_name',
            field=models.CharField(default='kazemi', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_request',
            name='person_state',
            field=models.CharField(choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('البرز', 'البرز'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('خراسان جنوبی', 'خراسان جنوبی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان شمالی', 'خراسان شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('فارس', 'فارس'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کردستان', 'کردستان'), ('کرمانشاه', 'کرمانشاه'), ('کرمان', 'کرمان'), ('کهکیلویه و بویراحمد', 'کهکیلویه و بویراحمد'), ('گلستان', 'گلستان'), ('گیلان', 'گیلان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('هرمزگان', 'هرمزگان'), ('مرکزی', 'مرکزی'), ('همدان', 'همدان'), ('یزد', 'یزد')], default='مازندران', max_length=100),
            preserve_default=False,
        ),
    ]
