# Generated by Django 4.2.6 on 2025-07-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0006_register_request_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_request',
            name='description',
        ),
        migrations.RemoveField(
            model_name='register_request',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='register_request',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='register_request',
            name='images',
        ),
        migrations.RemoveField(
            model_name='register_request',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='register_request',
            name='person_state',
        ),
    ]
