# Generated by Django 4.2.6 on 2025-07-10 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register_ad', '0007_remove_register_request_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_request',
            old_name='acknowledged',
            new_name='is_accepted',
        ),
        migrations.RenameField(
            model_name='register_request',
            old_name='waiting_for_confirmation',
            new_name='is_pending',
        ),
        migrations.AddField(
            model_name='register_request',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='register_request',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='register_request',
            name='waiting_for_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='register_request',
            name='acknowledged_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='register_request',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_ad.register_ad'),
        ),
        migrations.AlterField(
            model_name='register_request',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='register_request',
            name='recipient_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='register_request',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
