# Generated by Django 4.2.6 on 2025-07-10 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register_ad', '0008_rename_acknowledged_register_request_is_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Register_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1500)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_ad.register_ad')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
