# Generated by Django 4.2.6 on 2025-07-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0009_report_register_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_request',
            name='waiting_for_status',
        ),
    ]
