# Generated by Django 4.2.6 on 2025-07-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0010_remove_register_request_waiting_for_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_ad',
            name='first_name',
            field=models.CharField(default='m', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_ad',
            name='last_name',
            field=models.CharField(default='k', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_ad',
            name='selected_professional',
            field=models.CharField(default='s', max_length=30),
            preserve_default=False,
        ),
    ]
