# Generated by Django 4.2.6 on 2025-07-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0011_register_ad_first_name_register_ad_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_ad',
            name='fee',
            field=models.CharField(default='2', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register_ad',
            name='phone_number',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
