# Generated by Django 4.2.6 on 2025-07-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0012_register_ad_fee_alter_register_ad_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_ad',
            name='cooperation_kind',
            field=models.CharField(blank=True, choices=[('individual', 'فرد'), ('company', 'شرکت')], max_length=25, null=True),
        ),
    ]
