# Generated by Django 4.2.6 on 2025-07-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0013_alter_register_ad_cooperation_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_ad',
            name='skill',
            field=models.CharField(blank=True, choices=[('civil engineering', 'مهندسی عمران'), ('architectural engineering', 'مهندسی معمار'), ('electricity engineering', 'مهندسی برق'), ('facilities engineering', 'مهندسی تاسیسات'), ('surveyor', 'نقشه بردار'), ('mechanical machinery operator', 'اپراتور ماشین الات مکانیکی'), ('electerical technician', 'تکنسین برق'), ('plasterer', 'گچکار'), ('plumber', 'لوله کش'), ('painter', 'نقاش'), ('insulation specialist', 'متخصص عایقکاری'), ('brick layer', 'بنا'), ('mechanical installation technician', 'تکنسین تاسیسات مکانیکی'), ('carpenter', 'نجار'), ('tile work', 'کاشی کار'), ('stone work', 'سنگ کار'), ('simple_worker', 'کارگر ساده'), ('interior designer', 'طراح داخلی'), ('building supervisor', 'ناظر ساختمان'), ('armatorband', 'آرماتور بند'), ('welder', 'جوشکار'), ('metal skeleton specialist', 'متخصص اسکلت فلزی'), ('elevator installer', 'نصاب آسانسور'), ('security systems installer', 'نصاب سیستم های امنیتی'), ('renewable energy specialist', 'متخصص انرژی های تجدید پذیر'), ('waste expert', 'کارشناس پسماند'), ('building materials seller', 'فروشنده مصالح ساختمانی'), ('purchasing manager', 'مدیر خرید'), ('building cleaner', 'نظافتچی ساختمان'), ('heavy machinery operator', 'اپراتور ماشین آلات سنگین'), ('smart systems installer', 'نصاب سیستم های هوشمند')], max_length=45, null=True),
        ),
    ]
