# Generated by Django 4.2.6 on 2025-07-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0020_remove_register_ad_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_ad',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], default='active', max_length=10),
        ),
    ]
