# Generated by Django 4.2.6 on 2025-08-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0021_register_ad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_ad',
            name='gender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=3),
            preserve_default=False,
        ),
    ]
