# Generated by Django 4.2.6 on 2025-08-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0023_alter_register_ad_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_ad',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='register_ad',
            name='last_name',
        ),
    ]
