# Generated by Django 4.2.6 on 2025-08-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0024_rename_first_name_register_ad_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_ad',
            name='gender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='register_ad',
            name='name',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
