# Generated by Django 4.2.6 on 2025-08-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0025_alter_register_ad_gender_alter_register_ad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_ad',
            name='created_at',
            field=models.DateField(auto_now_add=True, max_length=10),
        ),
    ]
