# Generated by Django 4.2.6 on 2025-08-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_ad', '0027_alter_register_ad_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_ad',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
